### ISSUE TITLE
Huwelijksplanner redirect naar undefined

### ISSUE THREAD

**Issue by savitris** [frameless/utrecht-huwelijksplanner#147]
![Screenshot 2023-03-03 at 13 15 10](https://user-images.githubusercontent.com/11764984/222718028-6b76f51c-bf6a-4280-99c3-06dcdea57ab5.png)

Als ik op de Trouwen Plannen button klikt, dan word ik eerst naar een `trouw-opties/undefined ` en dan pas naar `trouw-opties/huwelijk`.

Dat is onhandig voor testing, maar waarschijnlijk ook voor screenreaders.

**Comment by savitris** [comment]
We hebben in het code geschreven, en gevonden dat best mogelijk het probleem hier ligt.
```javascript
export default function MultistepForm1() {
  const { t } = useTranslation(["common", "huwelijksplanner-step-1"]);
  const { push } = useRouter();
  const [weddingOptions, setWeddingOptions] = useState<string | undefined>();

  const onWeddingOptionsSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    push(`/trouw-opties/${weddingOptions}`);
  };

  const onWeddingOptionsClick = (event: any) => {
    setWeddingOptions(event.target.value);
  };
```

**Comment by bddjong** [comment]
Dit lijkt geen probleem meer te zien in de laatste versie.
