### ISSUE TITLE
Fix Codegen

### ISSUE THREAD

**Issue by Yolijn** [frameless/utrecht-huwelijksplanner#256]
In de #191 demo branch zit een hardcoded open-api.yml. In main worden de API `.yml` bestanden per stuk gedownload en gebuild.

Waarschijnlijk missen er nu ymls in de main, maar de hardcoded yml zorgt voor een error en gaat achterlopen.

- [x] Update lijst van te downloaden `yml`'s
- [x] Simplificeer de download en codegen scripts als dat mogelijk is

**Comment by bddjong** [comment]
https://github.com/frameless/utrecht-huwelijksplanner/pull/290
