### ISSUE TITLE
Fix hardcoded tekst en button op datum en tijd pagina

### ISSUE THREAD

**Issue by bddjong** [frameless/utrecht-huwelijksplanner#259]
### Beschrijving
Op stap 2, Kies een datum en tijd, staan er fields onder de datepicker die onlogisch zijn als de gebruiker nog geen dag heeft geselecteerd

<img width="803" alt="image" src="https://user-images.githubusercontent.com/24610692/232456502-d241b922-b151-4128-b6c3-eb0b22b5dafd.png">

#### Tasks

- Tekst onder datepicker alleen tonen als een dag is geselecteerd, of aangeven dat er geen beschikbare tijden zijn op de geselecteerde dag

**Comment by Yolijn** [comment]
Uitgebreid trouwen niet in MVP
