### ISSUE TITLE
Fix datepicker data in het verleden selecteren

### ISSUE THREAD

**Issue by bddjong** [frameless/utrecht-huwelijksplanner#260]
### Beschrijving
De datumpriker staat momenteel toe dat een gebruiker data in het verleden selecteert.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/24610692/232459511-75cc38f6-9931-4af7-b4cf-35643b7fa084.png">

### Tasks
- Dagen in het verleden niet selecteerbaar maken

**Comment by Yolijn** [comment]
Met Rene en Jeroen overleggen wat een goed 'startpunt' is van de calendar. Moet hij ook een datum in het verleden tonen uberhaubt?
