### ISSUE TITLE
Fix styling datepicker

### ISSUE THREAD

**Issue by Yolijn** [frameless/utrecht-huwelijksplanner#263]
De datepicker laat nu niet duidelijk zien welke data beschikbaar zijn. Ook zijn datums zonder tijdslots te selecteren.

- [x] Calendar navigatie style
- [x] Pas de stijl van de geselecteerde datum aan
- [x] Pas de stijl van de niet te selecteren data aan
- [x] Hover style

Figma: https://www.figma.com/file/msb3CfQBefPoruqNQ968Zh/Utrecht-Design-System?node-id=2903-6346&t=nq3fKct3C8GGPj6L-0

**Comment by bddjong** [comment]
https://github.com/nl-design-system/utrecht/pull/1699

**Comment by bddjong** [comment]
https://github.com/nl-design-system/utrecht/pull/1701
