### ISSUE TITLE
informatiebevestigingsgebied laat geen of inkorrekte kosten zien

### ISSUE THREAD

**Issue by savitris** [frameless/utrecht-huwelijksplanner#416]
## 1. Het blauwe vierkant (utrecht-spotlight-section--info) informatiebevestigingsgebied eerst laat de gekozen gegevens ( trouwsoort, datum en tijdslot) zien maar niet de kosten.

<img width="471" alt="Screenshot 2023-06-14 at 13 40 18" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/92cd36fd-3cda-4898-a812-cb2aab20b42b">

<img width="857" alt="Screenshot 2023-06-14 at 13 42 02" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/26394de9-dfdb-42a9-af67-7adefdf898c1">

## 2. Later op`voorgenomen-huwelijk/getuigen/succes` het informatiebevestigingsgebied laat de korrekte gekozen gegevens (zie punkt 1) niet zien en nu laat de kosten zien maar dit nummer blijft hetzelfde als man een extra trouwboekje kies of niet.
<img width="424" alt="Screenshot 2023-06-14 at 16 48 59" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/264b1526-3a89-4be8-892f-b4e9d02f080b">
<img width="615" alt="Screenshot 2023-06-14 at 16 53 34" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/44621f5c-696e-41d1-b164-aa9fff05aa2b">
<img width="794" alt="Screenshot 2023-06-14 at 17 37 43" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/13426297-9d5c-4312-a300-723f9ed4b20b">

**Comment by bddjong** [comment]
Resolved, oude versie van huwelijksplanner
