### ISSUE TITLE
extra's pagina problemen

### ISSUE THREAD

**Issue by savitris** [frameless/utrecht-huwelijksplanner#417]
Op de `extra` pagina

## 2. De enige manier om verder te gaan met het process is het `Deze wil ik hebben` button te klikken wat verwarrend is als men geen trouwboekje wil (en heeft geen geselecteerd).
<img width="615" alt="Screenshot 2023-06-14 at 16 53 34" src="https://github.com/frameless/utrecht-huwelijksplanner/assets/11764984/4d0bfab3-4c76-4069-9a0d-f1cfc74cf6b9">

**Comment by bddjong** [comment]
Dit is al opgelost in de main branch :)
